### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Adesoji1** [wearesulie/sulie#12]
Hi, Can I create the dockerfile?

**Comment by safaricd** [comment]
Hi @Adesoji1, thanks for the suggestion. Could you please explain what the purpose of the Dockerfile would be?

Just a heads up, Sulie is fully managed, meaning you don't have to deal with any model deployment or infrastructure whatsoever. At the moment, we provide the self-hosted capabilities only part of the Enterprise plan.
